/**
 * components/StreamingSummary.tsx — Streaming AI Summary Text
 * ============================================================
 *
 * Renders the plain-English summary of query results generated by the LLM.
 * This text arrives incrementally via SSE and builds up in real-time.
 *
 * TWO RENDERING MODES:
 *
 *   isStreaming === true  (status === "streaming")
 *     Content builds up word by word as "summary_chunk" SSE events arrive.
 *     A blinking cursor character (|) is appended after the last character.
 *     Cursor animation: CSS keyframes { 0%, 100% { opacity: 1 } 50% { opacity: 0 } }
 *     Gives a "live typing" feel that reassures the user the response is coming.
 *
 *   isStreaming === false  (status === "done")
 *     Full summary text rendered without cursor. Static, copyable text.
 *
 * TEXT CONTENT:
 *   The LLM summary may include:
 *     Bold text (**word**) -> <strong>word</strong>
 *     Numbered lists       -> render as <ol><li> elements
 *     Bullet lists         -> render as <ul><li> elements
 *   A lightweight inline parser handles these cases.
 *   Alternatively, render as pre-wrap plain text if simplicity is preferred.
 *
 * TYPOGRAPHY:
 *   Font:        system-serif or body font (not monospace)
 *   Size:        text-sm (14px)
 *   Color:       #e2e8f0 (primary text)
 *   Line height: 1.6 (comfortable reading for prose)
 *
 * Props:
 *   content: string      — Accumulated summary text so far
 *   isStreaming: boolean — Whether to show blinking cursor
 */