"""
scripts/ingest_schema.py — One-Time Schema Ingestion Script
===========================================================

RUN THIS ONCE before starting the app (and re-run whenever your DB schema changes).

WHAT IT DOES:
  1. Reads data/schema_metadata.json (either generated by extract_schema.py
     or hand-written following the required format).
  2. Extracts the "text" field from each table entry.
  3. Calls embedding_service.embed_texts() to batch-convert all schema texts
     into 1024-dimensional vectors using the BGE-M3 model.
  4. Calls pinecone_service.upsert_schemas() to store all vectors in Pinecone,
     using the table "id" field as the Pinecone vector ID.
  5. Prints progress (X tables ingested) and success/failure summary.

WHY THIS IS A SEPARATE SCRIPT (not automatic at startup):
  Embedding 100+ tables takes several minutes — you don't want this on every
  server restart. Schema only changes when you add/remove tables or columns,
  which is rare. Run it manually when needed.

INPUT FORMAT (schema_metadata.json):
  [
    {
      "id": "Driver",
      "text": "Table: Driver\\nDescription: Stores driver records\\nColumns:\\n- DriverId (int) [PRIMARY KEY]\\n..."
    }
  ]
  Each "id" = table name (used as the Pinecone vector ID for fetch_by_ids later).
  Each "text" = the full human-readable schema description that gets embedded.

RUN WITH:
  cd backend
  python scripts/ingest_schema.py

Imports: services/embedding_service, services/pinecone_service, config
"""